export const buttonStyles: Record<string, React.CSSProperties> = {
  primary: {
    backgroundColor: '#F14F4F',
    color: '#ffffff',
    padding: '22px 47px',
    fontSize: '16px',
    fontWeight: '400',
    borderRadius: '4px',
  },
  'primary-big': {
    backgroundColor: '#F14F4F',
    color: '#ffffff',
    padding: '22px 47px',
    fontSize: '16px',
    fontWeight: '400',
    borderRadius: '4px',
    width: '300px',
  },
  'primary-search': {
    backgroundColor: '#F14F4F',
    color: '#ffffff',
    height: '60px',
    padding: '0px 47px',
    fontSize: '16px',
    fontWeight: '400',
    borderRadius: '4px',
  },
  secondary: {
    backgroundColor: '#444B58',
    height: '67px',
    color: '#ffffff',
    fontSize: '16px',
    fontWeight: '400',
    borderRadius: '4px',
    width: '100%',
  },
  'secondary-border': {
    fontSize: '16px',
    fontWeight: '400',
    color: '#444B58',
    padding: '22px 42px 22px 42px',
    borderRadius: '4px',
    border: '1px solid rgb(68, 75, 88)',
    lineHeight: '23px',
  },
  tertiary: {
    fontSize: '16px',
    fontWeight: '400',
    color: '#444B58',
  },
};
